// REPLACE WITH BINDINGS FROM IM WHEN ITS MIGRATED TO TS
/**
 * All valid gamepad button bindings supported by Gameface
 * Includes uppercase names and lowercase aliases (xbox.*, playstation.*, etc.)
 * Based on coherent-gameface-interaction-manager gamepad-key-codes
 */
export type GamepadButton =
    | 'face-button-down'
    | 'face-button-left'
    | 'face-button-right'
    | 'face-button-top'
    | 'left-sholder'
    | 'right-sholder'
    | 'left-sholder-bottom'
    | 'right-sholder-bottom'
    | 'select'
    | 'start'
    | 'left-analogue-stick'
    | 'right-analogue-stick'
    | 'pad-up'
    | 'pad-down'
    | 'pad-left'
    | 'pad-right'
    | 'center-button'
    | 'playstation.x'
    | 'playstation.square'
    | 'playstation.circle'
    | 'playstation.triangle'
    | 'playstation.l1'
    | 'playstation.r1'
    | 'playstation.l2'
    | 'playstation.r2'
    | 'playstation.share'
    | 'playstation.options'
    | 'playstation.l3'
    | 'playstation.r3'
    | 'playstation.d-pad-up'
    | 'playstation.d-pad-down'
    | 'playstation.d-pad-left'
    | 'playstation.d-pad-right'
    | 'playstation.center'
    | 'xbox.a'
    | 'xbox.x'
    | 'xbox.b'
    | 'xbox.y'
    | 'xbox.lb'
    | 'xbox.rb'
    | 'xbox.lt'
    | 'xbox.rt'
    | 'xbox.view'
    | 'xbox.menu'
    | 'xbox.left-thumbstick'
    | 'xbox.right-thumbstick'
    | 'xbox.d-pad-up'
    | 'xbox.d-pad-down'
    | 'xbox.d-pad-left'
    | 'xbox.d-pad-right'
    | 'xbox.center';
