import { player } from "../types";

// `image` is a bare identifier for now (not a real asset path) — wired up
// properly once real player photos are added to the recipe.
const players: player[] = [
    {
        name: "Alejandro Vargas",
        nationality: "ar",
        country: "Argentina",
        position: 'fwd',
        age: 27,
        appearances: 35,
        is_injured: false,
        goals: 17,
        assists: 11,
        condition: 25,
        value: 76,
        image: 'fr-one',
    },
    {
        name: "Lucas Almeida",
        nationality: "br",
        country: "Brazil",
        position: 'fwd',
        age: 22,
        appearances: 28,
        is_injured: false,
        goals: 19,
        assists: 11,
        condition: 45,
        value: 95,
        image: 'it-one',
    },
    {
        name: "Sophie Brooks",
        nationality: "ca",
        country: "Canada",
        position: 'mid',
        age: 24,
        appearances: 29,
        is_injured: false,
        goals: 5,
        assists: 12,
        condition: 67,
        value: 44,
        image: 'ca-one',
    },
    {
        name: "Oumar Koné",
        nationality: "ci",
        country: "Ivory Coast",
        position: 'def',
        age: 29,
        appearances: 38,
        is_injured: false,
        goals: 1,
        assists: 5,
        condition: 88,
        value: 41,
        image: 'ci-one',
    },
    {
        name: "Camila Rojas",
        nationality: "cl",
        country: "Chile",
        position: 'mid',
        age: 25,
        appearances: 22,
        is_injured: false,
        goals: 7,
        assists: 9,
        condition: 55,
        value: 33,
        image: 'cl-one',
    },
    {
        name: "Maximilian Brandt",
        nationality: "de",
        country: "Germany",
        position: 'def',
        age: 26,
        appearances: 36,
        is_injured: false,
        goals: 3,
        assists: 6,
        condition: 90,
        value: 68,
        image: 'de-one',
    },
    {
        name: "Mette Andersen",
        nationality: "dk",
        country: "Denmark",
        position: 'gk',
        age: 30,
        appearances: 34,
        is_injured: false,
        goals: 0,
        assists: 2,
        condition: 82,
        value: 49,
        image: 'dk-one',
    },
    {
        name: "Omar Hassan",
        nationality: "eg",
        country: "Egypt",
        position: 'mid',
        age: 27,
        appearances: 30,
        is_injured: false,
        goals: 8,
        assists: 10,
        condition: 73,
        value: 52,
        image: 'eg-one',
    },
    {
        name: "Oliver Hayes",
        nationality: "eng",
        country: "England",
        position: 'gk',
        age: 33,
        appearances: 38,
        is_injured: false,
        goals: 0,
        assists: 1,
        condition: 61,
        value: 28,
        image: 'eng-one',
    },
    {
        name: "Carlos Fernández",
        nationality: "es",
        country: "Spain",
        position: 'fwd',
        age: 24,
        appearances: 32,
        is_injured: false,
        goals: 23,
        assists: 9,
        condition: 93,
        value: 94,
        image: 'de-two',
    },
    {
        name: "Antoine Moreau",
        nationality: "fr",
        country: "France",
        position: 'mid',
        age: 28,
        appearances: 40,
        is_injured: false,
        goals: 6,
        assists: 18,
        condition: 89,
        value: 78,
        image: 'fr-one',
    },
    {
        name: "Ciarán Murphy",
        nationality: "ie",
        country: "Ireland",
        position: 'def',
        age: 30,
        appearances: 24,
        is_injured: true,
        goals: 1,
        assists: 4,
        condition: 38,
        value: 31,
        image: 'eng-two',
    },
    {
        name: "Marco Ricci",
        nationality: "it",
        country: "Italy",
        position: 'def',
        age: 27,
        appearances: 33,
        is_injured: false,
        goals: 4,
        assists: 5,
        condition: 84,
        value: 63,
        image: 'it-one',
    },
    {
        name: "Khalid Al-Rashid",
        nationality: "jo",
        country: "Jordan",
        position: 'mid',
        age: 21,
        appearances: 16,
        is_injured: false,
        goals: 3,
        assists: 7,
        condition: 80,
        value: 35,
        image: 'ci-two',
    },
    {
        name: "Kaelen 'Cyber' Voss",
        nationality: "jp",
        country: "Japan",
        position: 'fwd',
        age: 24,
        appearances: 20,
        is_injured: false,
        goals: 20,
        assists: 7,
        condition: 85,
        value: 80,
        image: 'jp-one',
    },
    {
        name: "Ji-Ho Park",
        nationality: "kr",
        country: "South Korea",
        position: 'mid',
        age: 26,
        appearances: 35,
        is_injured: false,
        goals: 8,
        assists: 13,
        condition: 88,
        value: 71,
        image: 'kr-one',
    },
    {
        name: "Diego Herrera",
        nationality: "mx",
        country: "Mexico",
        position: 'def',
        age: 32,
        appearances: 39,
        is_injured: false,
        goals: 2,
        assists: 5,
        condition: 66,
        value: 29,
        image: 'vn-one',
    },
    {
        name: "Amara Okafor",
        nationality: "ng",
        country: "Nigeria",
        position: 'fwd',
        age: 19,
        appearances: 12,
        is_injured: false,
        goals: 9,
        assists: 4,
        condition: 94,
        value: 62,
        image: 'ng-one',
    },
    {
        name: "Rui Figueiredo",
        nationality: "pt",
        country: "Portugal",
        position: 'mid',
        age: 27,
        appearances: 36,
        is_injured: false,
        goals: 10,
        assists: 16,
        condition: 87,
        value: 82,
        image: 'fr-one',
    },
    {
        name: "Stefan Nikolić",
        nationality: "rs",
        country: "Serbia",
        position: 'def',
        age: 34,
        appearances: 42,
        is_injured: false,
        goals: 2,
        assists: 4,
        condition: 57,
        value: 21,
        image: 'de-two',
    },
    {
        name: "Erik Lindqvist",
        nationality: "se",
        country: "Sweden",
        position: 'gk',
        age: 23,
        appearances: 19,
        is_injured: false,
        goals: 0,
        assists: 0,
        condition: 78,
        value: 38,
        image: 'eng-two',
    },
    {
        name: "Maya Webb",
        nationality: "us",
        country: "United States",
        position: 'fwd',
        age: 25,
        appearances: 27,
        is_injured: false,
        goals: 13,
        assists: 7,
        condition: 83,
        value: 69,
        image: 'us-one',
    },
    {
        name: "Mai Nguyen",
        nationality: "vn",
        country: "Vietnam",
        position: 'def',
        age: 26,
        appearances: 29,
        is_injured: false,
        goals: 1,
        assists: 3,
        condition: 68,
        value: 22,
        image: 'vn-two',
    },
    {
        name: "Gabriel Souza",
        nationality: "br",
        country: "Brazil",
        position: 'mid',
        age: 21,
        appearances: 15,
        is_injured: false,
        goals: 6,
        assists: 10,
        condition: 95,
        value: 77,
        image: 'it-one',
    },
    {
        name: "Hiroshi Tanaka",
        nationality: "jp",
        country: "Japan",
        position: 'mid',
        age: 29,
        appearances: 34,
        is_injured: false,
        goals: 8,
        assists: 15,
        condition: 79,
        value: 53,
        image: 'jp-two',
    },
    {
        name: "Felix Wagner",
        nationality: "de",
        country: "Germany",
        position: 'mid',
        age: 23,
        appearances: 19,
        is_injured: true,
        goals: 5,
        assists: 8,
        condition: 32,
        value: 55,
        image: 'de-one',
    },
    {
        name: "Jack Thornton",
        nationality: "eng",
        country: "England",
        position: 'mid',
        age: 25,
        appearances: 31,
        is_injured: false,
        goals: 12,
        assists: 9,
        condition: 81,
        value: 72,
        image: 'eng-two',
    },
    {
        name: "Rafael Costa",
        nationality: "br",
        country: "Brazil",
        position: 'def',
        age: 30,
        appearances: 41,
        is_injured: true,
        goals: 2,
        assists: 4,
        condition: 47,
        value: 34,
        image: 'fr-one',
    },
    {
        name: "Jonas Keller",
        nationality: "de",
        country: "Germany",
        position: 'gk',
        age: 31,
        appearances: 40,
        is_injured: false,
        goals: 0,
        assists: 0,
        condition: 86,
        value: 53,
        image: 'de-two',
    },
    {
        name: "Harry Whitmore",
        nationality: "eng",
        country: "England",
        position: 'fwd',
        age: 35,
        appearances: 29,
        is_injured: false,
        goals: 11,
        assists: 5,
        condition: 58,
        value: 18,
        image: 'eng-one',
    },
    {
        name: "Sora Yamamoto",
        nationality: "jp",
        country: "Japan",
        position: 'def',
        age: 28,
        appearances: 33,
        is_injured: false,
        goals: 1,
        assists: 3,
        condition: 84,
        value: 50,
        image: 'jp-four',
    },
    {
        name: "Renata Oliveira",
        nationality: "br",
        country: "Brazil",
        position: 'fwd',
        age: 18,
        appearances: 7,
        is_injured: false,
        goals: 3,
        assists: 2,
        condition: 91,
        value: 61,
        image: 'br-one',
    },
    {
        name: "Pedro Cunha",
        nationality: "pt",
        country: "Portugal",
        position: 'fwd',
        age: 22,
        appearances: 20,
        is_injured: false,
        goals: 11,
        assists: 5,
        condition: 82,
        value: 66,
        image: 'eng-one',
    },
    {
        name: "Yoon Ji-Soo",
        nationality: "kr",
        country: "South Korea",
        position: 'def',
        age: 28,
        appearances: 32,
        is_injured: false,
        goals: 2,
        assists: 3,
        condition: 86,
        value: 57,
        image: 'kr-three',
    },
    {
        name: "Ivan Kovač",
        nationality: "rs",
        country: "Serbia",
        position: 'fwd',
        age: 24,
        appearances: 23,
        is_injured: false,
        goals: 15,
        assists: 6,
        condition: 75,
        value: 73,
        image: 'de-two',
    },
];

export default players;
