// THIS FILE IS AUTO-GENERATED BY scripts/images/image-types.mjs. DO NOT EDIT.
// Regenerate with `npm run gen-images`, or let the dev server do it.

import type { ParentComponent } from 'solid-js';
import type { ImageComponentProps } from '../shared/types';

/** `src` is filled in by the images plugin from the path written after `Image.`. */
type ImageLeaf = ParentComponent<Omit<ImageComponentProps, 'src'>>;

export interface ImageTree {
    icons: {
        gamepad: {
            ps5: {
                circle: ImageLeaf;
                cross: ImageLeaf;
                dpad: ImageLeaf;
                dpadDown: ImageLeaf;
                dpadLeft: ImageLeaf;
                dpadRight: ImageLeaf;
                dpadUp: ImageLeaf;
                l1: ImageLeaf;
                l2: ImageLeaf;
                leftStick: ImageLeaf;
                leftStickPress: ImageLeaf;
                microphone: ImageLeaf;
                options: ImageLeaf;
                optionsAlt: ImageLeaf;
                r1: ImageLeaf;
                r2: ImageLeaf;
                rightStick: ImageLeaf;
                rightStickClick: ImageLeaf;
                share: ImageLeaf;
                shareAlt: ImageLeaf;
                square: ImageLeaf;
                touchPad: ImageLeaf;
                triangle: ImageLeaf;
            };
            switch: {
                a: ImageLeaf;
                b: ImageLeaf;
                down: ImageLeaf;
                dpad: ImageLeaf;
                dpadDown: ImageLeaf;
                dpadLeft: ImageLeaf;
                dpadRight: ImageLeaf;
                dpadUp: ImageLeaf;
                home: ImageLeaf;
                lb: ImageLeaf;
                left: ImageLeaf;
                leftStick: ImageLeaf;
                leftStickClick: ImageLeaf;
                lt: ImageLeaf;
                minus: ImageLeaf;
                plus: ImageLeaf;
                rb: ImageLeaf;
                right: ImageLeaf;
                rightStick: ImageLeaf;
                rightStickClick: ImageLeaf;
                rt: ImageLeaf;
                square: ImageLeaf;
                up: ImageLeaf;
                x: ImageLeaf;
                y: ImageLeaf;
            };
            weapon: ImageLeaf;
            xbox: {
                a: ImageLeaf;
                b: ImageLeaf;
                dpad: ImageLeaf;
                dpadDown: ImageLeaf;
                dpadLeft: ImageLeaf;
                dpadRight: ImageLeaf;
                dpadUp: ImageLeaf;
                lb: ImageLeaf;
                leftStick: ImageLeaf;
                leftStickPress: ImageLeaf;
                lt: ImageLeaf;
                menu: ImageLeaf;
                rb: ImageLeaf;
                rightStick: ImageLeaf;
                rightStickPress: ImageLeaf;
                rt: ImageLeaf;
                share: ImageLeaf;
                view: ImageLeaf;
                x: ImageLeaf;
                y: ImageLeaf;
            };
        };
        hud: {
            crosshair: ImageLeaf;
            grenade: ImageLeaf;
            placeholder: ImageLeaf;
            weapon: ImageLeaf;
        };
    };
    wheel: {
        gameMessageAchievmentIcon: ImageLeaf;
        weapon1: ImageLeaf;
        weapon2: ImageLeaf;
        weapon3: ImageLeaf;
        weapon4: ImageLeaf;
        weapon5: ImageLeaf;
        weapon6: ImageLeaf;
    };
}
