import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { globSync } from 'glob';

export const IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'webp'];

/**
 * Turns a file or folder name into the key it is written as after `Image.` -
 * `round-star` becomes `roundStar`, so `<Image.icons.roundStar />`.
 *
 * @param {string} name The file or folder name to normalize.
 * @param {string} file The image path, used only for error messages.
 * @returns {string} The normalized, camelCased key.
 */
function normalizeImageKey(name, file) {
    const key = name
        .replace(/[^a-zA-Z0-9]+(.)?/g, (_, chr) => (chr ? chr.toUpperCase() : ''))
        .replace(/^[A-Z]/, (c) => c.toLowerCase());

    if (key === '') {
        throw new Error(
            `Image "${file}" has no usable name: it contains no letters or digits. ` +
            `Rename it to something like "myImage.png".`
        );
    }

    if (/^[0-9]/.test(key)) {
        throw new Error(
            `Image "${file}" produces the key "${key}", which starts with a digit and cannot be written after \`Image.\`. ` +
            `Rename it to start with a letter, e.g. "image${key}.png".`
        );
    }

    return key;
}

/**
 * Every image under `assetsDir`, keyed the way it is written after `Image.`.
 *
 * @param {string} assetsDir Folder whose images are exposed on `Image`.
 * @returns {Map<string, string>} `icons.gamepad.a` -> absolute path of `icons/gamepad/a.png`.
 */
export function scanImages(assetsDir) {
    const root = path.resolve(assetsDir);
    const images = new Map();

    const pattern = `**/*.{${IMAGE_EXTENSIONS.join(',')}}`;
    for (const file of globSync(pattern, { cwd: root, posix: true })) {
        const key = file
            .replace(/\.[^/.]+$/, '')
            .split('/')
            .map((part) => normalizeImageKey(part, file))
            .join('.');

        if (images.has(key)) {
            throw new Error(`Duplicate image key "${key}" for file "${file}".`);
        }
        images.set(key, path.join(root, file));
    }

    return images;
}

/** `{ icons: { gamepad: { a: '/abs/a.png' } } }` - a string marks an image (its path), objects are folders. */
function buildTypeTree(images) {
    const tree = {};

    for (const [key, file] of images) {
        const parts = key.split('.');
        let level = tree;

        parts.forEach((part, index) => {
            const isImage = index === parts.length - 1;
            const existing = level[part];

            // `a.png` next to an `a/` folder would need `Image.x.a` to be both a component and an object.
            if (isImage ? existing !== undefined : typeof existing === 'string') {
                throw new Error(`"${parts.slice(0, index + 1).join('/')}" is both an image and a folder. Rename one of them.`);
            }

            if (isImage) level[part] = file;
            else level = level[part] ??= {};
        });
    }

    return tree;
}

/**
 * Hovering an image key shows the image, with a link that opens it. The path is
 * absolute because VS Code resolves hover links against the file being hovered.
 */
function renderPreview(file, indent) {
    const uri = pathToFileURL(file).href;
    return [
        `${indent}/**`,
        `${indent} * ![${path.basename(file)}](${uri})`,
        `${indent} *`,
        `${indent} * [Open ${path.basename(file)}](${uri})`,
        `${indent} */`,
    ].join('\n');
}

function renderTypeTree(tree, indent) {
    return Object.entries(tree)
        .map(([key, value]) => typeof value === 'string'
            ? `${renderPreview(value, indent)}\n${indent}${key}: ImageLeaf;`
            : `${indent}${key}: {\n${renderTypeTree(value, `${indent}    `)}\n${indent}};`)
        .join('\n');
}

function generateTypes(images) {
    return `// THIS FILE IS AUTO-GENERATED BY scripts/images/image-types.mjs. DO NOT EDIT.
// Regenerate with \`npm run gen-images\`, or let the dev server do it.

import type { ParentComponent } from 'solid-js';
import type { ImageComponentProps } from '../shared/types';

/** \`src\` is filled in by the images plugin from the path written after \`Image.\`. */
type ImageLeaf = ParentComponent<Omit<ImageComponentProps, 'src'>>;

export interface ImageTree {
${renderTypeTree(buildTypeTree(images), '    ')}
}
`;
}

/**
 * Writes the `ImageTree` interface for `images` to `typesFile`.
 *
 * @param {Map<string, string>} images The result of `scanImages`.
 * @param {string} typesFile File the types are written to.
 */
export function writeImageTypes(images, typesFile) {
    const sorted = [...images].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
    const content = generateTypes(sorted);
    const current = fs.existsSync(typesFile) ? fs.readFileSync(typesFile, 'utf8') : null;

    // Only on a real change, so a rescan does not wake the TypeScript server for nothing.
    if (content !== current) fs.writeFileSync(typesFile, content);
}
