import fs from 'node:fs';
import path from 'node:path';
import { globSync } from 'glob';

export const IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'webp'];

/**
 * Turns a file or folder name into the key it is written as after `Image.` -
 * `round-star` becomes `roundStar`, so `<Image.icons.roundStar />`.
 *
 * @param {string} name The file or folder name to normalize.
 * @param {string} file The image path, used only for error messages.
 * @returns {string} The normalized, camelCased key.
 */
function normalizeImageKey(name, file) {
    const key = name
        .replace(/[^a-zA-Z0-9]+(.)?/g, (_, chr) => (chr ? chr.toUpperCase() : ''))
        .replace(/^[A-Z]/, (c) => c.toLowerCase());

    if (key === '') {
        throw new Error(
            `Image "${file}" has no usable name: it contains no letters or digits. ` +
            `Rename it to something like "myImage.png".`
        );
    }

    if (/^[0-9]/.test(key)) {
        throw new Error(
            `Image "${file}" produces the key "${key}", which starts with a digit and cannot be written after \`Image.\`. ` +
            `Rename it to start with a letter, e.g. "image${key}.png".`
        );
    }

    return key;
}

/**
 * Every image under `assetsDir`, keyed the way it is written after `Image.`.
 *
 * @param {string} assetsDir Folder whose images are exposed on `Image`.
 * @returns {Map<string, string>} `icons.gamepad.a` -> absolute path of `icons/gamepad/a.png`.
 */
export function scanImages(assetsDir) {
    const root = path.resolve(assetsDir);
    const images = new Map();

    const pattern = `**/*.{${IMAGE_EXTENSIONS.join(',')}}`;
    for (const file of globSync(pattern, { cwd: root, posix: true })) {
        const key = file
            .replace(/\.[^/.]+$/, '')
            .split('/')
            .map((part) => normalizeImageKey(part, file))
            .join('.');

        images.set(key, path.join(root, file));
    }

    return images;
}

/** `{ icons: { gamepad: { a: null } } }` - `null` marks an image, objects are folders. */
function buildTypeTree(keys) {
    const tree = {};

    for (const key of keys) {
        const parts = key.split('.');
        let level = tree;

        parts.forEach((part, index) => {
            const isImage = index === parts.length - 1;
            const existing = level[part];

            // `a.png` next to an `a/` folder would need `Image.x.a` to be both a component and an object.
            if (isImage ? existing !== undefined : existing === null) {
                throw new Error(`"${parts.slice(0, index + 1).join('/')}" is both an image and a folder. Rename one of them.`);
            }

            if (isImage) level[part] = null;
            else level = level[part] ??= {};
        });
    }

    return tree;
}

function renderTypeTree(tree, indent) {
    return Object.entries(tree)
        .map(([key, value]) => value === null
            ? `${indent}${key}: ImageLeaf;`
            : `${indent}${key}: {\n${renderTypeTree(value, `${indent}    `)}\n${indent}};`)
        .join('\n');
}

function generateTypes(keys) {
    return `// THIS FILE IS AUTO-GENERATED BY scripts/images/image-types.mjs. DO NOT EDIT.
// Regenerate with \`npm run gen-images\`, or let the dev server do it.

import type { ParentComponent } from 'solid-js';
import type { ImageProps } from '@components/Media/Image/Image';

/** \`src\` is filled in by the images plugin from the path written after \`Image.\`. */
type ImageLeaf = ParentComponent<Omit<ImageProps, 'src'>>;

export interface ImageTree {
${renderTypeTree(buildTypeTree(keys), '    ')}
}
`;
}

/**
 * Writes the `ImageTree` interface for `images` to `typesFile`.
 *
 * @param {Map<string, string>} images The result of `scanImages`.
 * @param {string} typesFile File the types are written to.
 */
export function writeImageTypes(images, typesFile) {
    const content = generateTypes([...images.keys()].sort());
    const current = fs.existsSync(typesFile) ? fs.readFileSync(typesFile, 'utf8') : null;

    // Only on a real change, so a rescan does not wake the TypeScript server for nothing.
    if (content !== current) fs.writeFileSync(typesFile, content);
}
