export const MAPPINGS = {
    // Letters
    KeyA: "A",
    KeyB: "B",
    KeyC: "C",
    KeyD: "D",
    KeyE: "E",
    KeyF: "F",
    KeyG: "G",
    KeyH: "H",
    KeyI: "I",
    KeyJ: "J",
    KeyK: "K",
    KeyL: "L",
    KeyM: "M",
    KeyN: "N",
    KeyO: "O",
    KeyP: "P",
    KeyQ: "Q",
    KeyR: "R",
    KeyS: "S",
    KeyT: "T",
    KeyU: "U",
    KeyV: "V",
    KeyW: "W",
    KeyX: "X",
    KeyY: "Y",
    KeyZ: "Z",

    // Digits
    Digit0: "0",
    Digit1: "1",
    Digit2: "2",
    Digit3: "3",
    Digit4: "4",
    Digit5: "5",
    Digit6: "6",
    Digit7: "7",
    Digit8: "8",
    Digit9: "9",

    // Function keys
    F1: "F1",
    F2: "F2",
    F3: "F3",
    F4: "F4",
    F5: "F5",
    F6: "F6",
    F7: "F7",
    F8: "F8",
    F9: "F9",
    F10: "F10",
    F11: "F11",
    F12: "F12",
    F13: "F13",
    F14: "F14",
    F15: "F15",
    F16: "F16",
    F17: "F17",
    F18: "F18",
    F19: "F19",
    F20: "F20",
    F21: "F21",
    F22: "F22",
    F23: "F23",
    F24: "F24",

    // Numpad
    Numpad0: "Num 0",
    Numpad1: "Num 1",
    Numpad2: "Num 2",
    Numpad3: "Num 3",
    Numpad4: "Num 4",
    Numpad5: "Num 5",
    Numpad6: "Num 6",
    Numpad7: "Num 7",
    Numpad8: "Num 8",
    Numpad9: "Num 9",
    NumpadAdd: "+",
    NumpadSubtract: "-",
    NumpadMultiply: "*",
    NumpadDivide: "/",
    NumpadDecimal: ".",
    NumpadComma: ",",
    NumpadEnter: "Num Enter",
    NumpadEqual: "Num =",

    // Symbols
    Backquote: "`",
    Minus: "-",
    Equal: "=",
    BracketLeft: "[",
    BracketRight: "]",
    Backslash: "\\",
    Semicolon: ";",
    Quote: "'",
    Comma: ",",
    Period: ".",
    Slash: "/",

    // Modifier keys
    ShiftLeft: "L Shift",
    ShiftRight: "R Shift",
    ControlLeft: "L Ctrl",
    ControlRight: "R Ctrl",
    AltLeft: "L Alt",
    AltRight: "R Alt",
    MetaLeft: "L Meta",
    MetaRight: "R Meta",

    // Other special keys
    Escape: "Esc",
    Tab: "Tab",
    CapsLock: "Caps",
    Space: "Space",
    Enter: "Enter",
    Backspace: "Back",
    Delete: "Del",
    Insert: "Ins",
    Home: "Home",
    End: "End",
    PageUp: "PgUp",
    PageDown: "PgDn",

    ArrowUp: "Up",
    ArrowDown: "Down",
    ArrowLeft: "Left",
    ArrowRight: "Right",

    PrintScreen: "PrtSc",
    ScrollLock: "Scroll",
    Pause: "Pause",
    ContextMenu: "Menu",

    // Extra keys
    NumLock: "NumLock",
    AudioVolumeMute: "Mute",
    AudioVolumeDown: "Vol-",
    AudioVolumeUp: "Vol+",
    MediaTrackNext: "Next",
    MediaTrackPrevious: "Prev",
    MediaStop: "Stop",
    MediaPlayPause: "Play/Pause",
    BrowserBack: "BrowserBack",
    BrowserForward: "BrowserForward",
    BrowserRefresh: "BrowserRefresh",
    BrowserStop: "BrowserStop",
    BrowserSearch: "BrowserSearch",
    BrowserFavorites: "BrowserFav",
    BrowserHome: "BrowserHome",

    // Mouse buttons
    "0": "LMB",
    "1": "MMB",
    "2": "RMB",
    "3": "BMB",
    "4": "FMB",

    // Mouse wheel
    "WheelUp": "Wheel Up",
    "WheelDown": "Wheel Down",
} as const;

export type BindingCode = keyof typeof MAPPINGS;          // e.g. "KeyW" | "ArrowUp" | "0" | "WheelUp" | ...
export type BindingLabel = (typeof MAPPINGS)[BindingCode]; // e.g. "A" | "Up" | "LMB" | "Wheel Up" | ...