export const countries = [
  { name: "Argentina", code: "ar" },
  { name: "Brazil", code: "br" },
  { name: "Canada", code: "ca" },
  { name: "Ivory Coast", code: "ci" },
  { name: "Chile", code: "cl" },
  { name: "Germany", code: "de" },
  { name: "Denmark", code: "dk" },
  { name: "Egypt", code: "eg" },
  { name: "England", code: "eng" },
  { name: "France", code: "fr" },
  { name: "Ireland", code: "ie" },
  { name: "Italy", code: "it" },
  { name: "Jordan", code: "jo" },
  { name: "Japan", code: "jp" },
  { name: "South Korea", code: "kr" },
  { name: "Mexico", code: "mx" },
  { name: "Nigeria", code: "ng" },
  { name: "Portugal", code: "pt" },
  { name: "Serbia", code: "rs" },
  { name: "Sweden", code: "se" },
  { name: "United States", code: "us" },
  { name: "Vietnam", code: "vn" },
  { name: "Spain", code: "es" },
];
