name: GamefaceUI release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Tag current commit with version
        run: |
          VERSION=$(jq -r .version package.json)
          git tag -a v$VERSION -m "Changelog: https://gameface-ui.coherent-labs.com/changelog/$VERSION"
          git push origin "v$VERSION"
